server {
  listen 8001;
  location / {
    default_type application/json;
    content_by_lua_block {
      Kong.admin_content()
    }
    header_filter_by_lua_block {
      Kong.admin_header_filter()
    }
  }
}
